CREATE TABLE version (
  version_id INTEGER AUTO_INCREMENT,
  version INTEGER NOT NULL,
  last_updated TIMESTAMP NOT NULL
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (version_id)
);